name: Lint and Format

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

permissions:
  contents: read

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier check
        id: prettier
        run: npm run format:check
        continue-on-error: true

      - name: Annotate ESLint failure
        if: steps.eslint.outcome == 'failure'
        run: |
          echo "::error title=ESLint found issues::Run 'npm run lint:fix' locally to automatically fix problems where possible, then commit and push."

      - name: Annotate Prettier failure
        if: steps.prettier.outcome == 'failure'
        run: |
          echo "::error title=Prettier formatting issues::Run 'npm run format' locally to format files, then commit and push."

      - name: Fail if any issues were found
        if: steps.eslint.outcome == 'failure' || steps.prettier.outcome == 'failure'
        run: |
          echo "Lint and/or format checks failed. See logs above."
          exit 1
